# Generated by Django 4.1.7 on 2023-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awsimage',
            name='images',
        ),
        migrations.AddField(
            model_name='awsimage',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='images/'),
        ),
    ]
